apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
data:
  key1: {{ .Values.myobj.myproperty1 | quote }}
  key2: {{ .Values.myobj.myproperty2 | quote }}
