replicaCount: 1

image:
  repository: alpine
  tag: "3.19"
  pullPolicy: IfNotPresent

# These probes will always fail because Alpine container has no HTTP server
startupProbe:
  httpGet:
    path: /health
    port: 8080
  initialDelaySeconds: 5
  periodSeconds: 5
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /ready  
    port: 8080
  initialDelaySeconds: 10
  periodSeconds: 5
  failureThreshold: 3